cmake_minimum_required(VERSION 3.10)
project(CoreHeartbeat CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(CoreRelay CoreRelay.cpp)
add_executable(Heartbeat Heartbeat.cpp)
add_executable(Sister Sister.cpp)
add_executable(Dummy Dummy.cpp)
add_executable(TestMutex TestMutex.cpp)
add_executable(TestParsing TestParsing.cpp)
add_executable(TestDrops TestDrops.cpp)
add_executable(TestPacts TestPacts.cpp)
add_executable(Console Console.cpp)

if(WIN32)
    target_link_libraries(CoreRelay ws2_32)
    target_link_libraries(Heartbeat ws2_32)
    target_link_libraries(Sister ws2_32)
    target_link_libraries(Dummy ws2_32)
    target_link_libraries(Console ws2_32)
    target_link_libraries(TestMutex ws2_32)
    target_link_libraries(TestParsing ws2_32)
    target_link_libraries(TestDrops ws2_32)
    target_link_libraries(TestPacts ws2_32)
else()
    target_link_libraries(CoreRelay pthread)
    target_link_libraries(Heartbeat pthread)
    target_link_libraries(Sister pthread)
    target_link_libraries(Dummy pthread)
    target_link_libraries(Console pthread)
    target_link_libraries(TestMutex pthread)
    target_link_libraries(TestParsing pthread)
    target_link_libraries(TestDrops pthread)
    target_link_libraries(TestPacts pthread)
endif()
